services:
  - type: web
    name: moliya-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PAYMENTS_TOKEN
        sync: false
